services:
  frontend:
    image: dev/vq-clock
    build:
      context: .
      target: development
      args:
        DOCKER_BUILDKIT: 1
    volumes:
      - ./src:/app/src
    ports:
      - "8080:8080"
